######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 2 00:59:10 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/mainWindow.h src/pageTab.h
SOURCES += src/main.cpp src/mainWindow.cpp src/pageTab.cpp
RESOURCES += src/icons.qrc
