######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 27 19:34:03 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
