#!/bin/bash

if [ $# -ne 2 ]; then
    echo -e "\nusage: ./grab_dbg_imgs MEDSName numimgspertestset";
    echo -e "\nMEDSName is the name of the MEDS module tested";
    echo -e "\nGrabs all of the tracker images for each test for the";
    echo -e " specified MEDS module, names them uniquely and brings them"
    echo -e " up to this directory. Assumes names are test1-test4. The ";
    echo -e "second argument is the number of images per test set.\n";
else
    MEDS=$1;
    numimgs=$2;
    testnum=4; #fixed for now
    i=1;
    while(( $i<=$testnum ))
    do
        testname="test"$( printf '%d' $i );
        j=1;
        while(( $j<=$numimgs ))
        do
            cp $testname/$MEDS/math_results/all/dbg/$numimgs/hyp_tracker_final.png $MEDS"_testset_"$i"_dbgim"$j".png";
            j=$(($j+1))
        done
        i=$(($i+1))
    done
fi
