#!/bin/bash

if [ $# -ne 2 -a $# -ne 3 ]; then
    echo -e "\nusage: rename_pngs inputdir outputdir";
    echo -e "\ninputdir - directory containing png's to be renamed";
    echo "outputdir - directory to copy renamed .png's into";
    echo "renames and copies all pngs in inputdir into outputdir.";
    echo -e "*doesn't change names of originals*\n";
    echo -e "Optionally you can rename a different extension";
    echo -e " like tif for instance by specifying that as the";
    echo -e " third argument (without the . at the front)\n";
else
    curdir=$( pwd | tr -d '\n');
    inputdir=$1;
    outputdir=$2;
    #optional extension argument
    ext=$3
    if [ -z "$3" ]; then
        ext="png"
    fi
    num=$(ls $inputdir/*.$ext | wc -l);
    echo -e "renaming $(($num)) "$( printf '%s' $ext )"'s\n";
    i=1;
    mkdir $outputdir;
    echo -e "progress:\n";
    while (( $i<=$num ))
    do
        file=$(ls $inputdir/*.$ext | head -n $i | tail -n 1 | tr -d '\n');
        echo -e "\n=================filename:"$( printf '%d.%s' $(($i)) $ext )" --- originalname:"$file"=================\n" >> $outputdir"/files_info";
        #identify -verbose -ping $file >> $outputdir"/files_info";
        cp $file $outputdir"/"$( printf '%d.%s' $(($i)) $ext );
        echo -en "$(($i)) ===> $(($num))\r"
        i=$(($i+1));
    done
    echo -e "\nComplete!"
fi    

        
