######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 4 16:08:47 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/mainWindow.h src/pageTab.h
SOURCES += src/main.cpp src/mainWindow.cpp src/pageTab.cpp
RESOURCES += src/icons.qrc
